# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200410_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='qq',
            field=models.CharField(max_length=10, verbose_name='qq号码'),
        ),
    ]
