# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200410_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProDuct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('P_image', models.CharField(max_length=256, verbose_name='产品图样')),
                ('detailed', models.TextField(verbose_name='详细说明')),
                ('trait_one', models.CharField(max_length=256, verbose_name='特点1')),
                ('trait_two', models.CharField(max_length=256, verbose_name='特点2')),
                ('trait_there', models.CharField(max_length=256, verbose_name='特点3')),
                ('trait_four', models.CharField(max_length=256, verbose_name='特点4')),
                ('trait_five', models.CharField(max_length=256, verbose_name='特点5')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['id'],
            },
        ),
    ]
