# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('image', models.CharField(max_length=256, verbose_name='产品图样')),
                ('detailed', models.TextField(verbose_name='详细说明')),
                ('one', models.CharField(max_length=256, verbose_name='特点1')),
                ('two', models.CharField(max_length=256, verbose_name='特点2')),
                ('there', models.CharField(max_length=256, verbose_name='特点3')),
                ('four', models.CharField(max_length=256, verbose_name='特点4')),
                ('five', models.CharField(max_length=256, verbose_name='特点5')),
            ],
            options={
                'verbose_name': '案例',
                'verbose_name_plural': '案例',
                'ordering': ['id'],
            },
        ),
    ]
