# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-13 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_casedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='内容')),
                ('issuper', models.IntegerField(verbose_name='是否为管理员发言')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天',
                'verbose_name_plural': '聊天',
                'ordering': ['id'],
            },
        ),
    ]
