# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-14 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chatt_userne'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatt',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
    ]
